"""Initial Migration

Revision ID: 8f9bbb512c3e
Revises: 
Create Date: 2025-03-07 15:23:24.111178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9bbb512c3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_news',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_stock_news_id'), 'stock_news', ['id'], unique=False)
    op.create_index(op.f('ix_stock_news_symbol'), 'stock_news', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_news_symbol'), table_name='stock_news')
    op.drop_index(op.f('ix_stock_news_id'), table_name='stock_news')
    op.drop_table('stock_news')
    # ### end Alembic commands ###
